/* This file is generated by `npm run translate:vi`. */
/* Do not edit by hand. */

export type ViSeedDescription = { summary: string; details: string };

// Empty placeholder until translations are generated locally.
export const viSeedDescriptions: Record<string, ViSeedDescription> = {};

