/* eslint-disable no-console */
import { writeFile } from "node:fs/promises";
import path from "node:path";

import type { Idea } from "../src/types";
import { buildSeedIdeas } from "../src/lib/seed.ts";

type TranslationRow = {
  summary: string;
  details: string;
};

const API_KEY = process.env.GOOGLE_TRANSLATE_API_KEY;

const SOURCE = "en";
const TARGET = "vi";

const stripCites = (value: string) => value.replace(/\[cite:\s*\d+\]/gi, "").trim();

const escapeTsString = (value: string) =>
  value
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");

const decodeHtmlEntities = (value: string) =>
  value
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"');

const translateBatch = async (texts: string[]) => {
  if (!API_KEY) {
    throw new Error("Missing GOOGLE_TRANSLATE_API_KEY env var.");
  }

  const endpoint = `https://translation.googleapis.com/language/translate/v2?key=${encodeURIComponent(API_KEY)}`;
  const response = await fetch(endpoint, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      q: texts,
      source: SOURCE,
      target: TARGET,
      format: "text",
    }),
  });

  if (!response.ok) {
    const body = await response.text().catch(() => "");
    throw new Error(`Translate API failed: ${response.status} ${response.statusText} ${body}`.trim());
  }

  const json = (await response.json()) as {
    data?: { translations?: Array<{ translatedText: string }> };
  };

  const translations = json.data?.translations ?? [];
  if (translations.length !== texts.length) {
    throw new Error(`Translate API returned ${translations.length} translations for ${texts.length} inputs.`);
  }

  return translations.map((row) => decodeHtmlEntities(row.translatedText).trim());
};

const chunk = <T,>(items: T[], size: number) => {
  const out: T[][] = [];
  for (let index = 0; index < items.length; index += size) {
    out.push(items.slice(index, index + size));
  }
  return out;
};

const main = async () => {
  const seedIdeas = buildSeedIdeas().filter((idea) => idea.source === "seed");

  // We translate the currently stored English summaries/details. Keep cites out of the translation.
  const toTranslate: Array<{ id: string; field: "summary" | "details"; text: string; original: string }> = [];
  seedIdeas.forEach((idea) => {
    (["summary", "details"] as const).forEach((field) => {
      const original = idea[field];
      const text = stripCites(original);
      toTranslate.push({ id: idea.id, field, text, original });
    });
  });

  const unique = new Map<string, string>();
  toTranslate.forEach((row) => {
    if (!row.text) return;
    unique.set(row.text, row.text);
  });

  const uniqueTexts = Array.from(unique.keys());
  console.log(`Seed ideas: ${seedIdeas.length}`);
  console.log(`Unique text blocks to translate: ${uniqueTexts.length}`);

  const translated = new Map<string, string>();
  const batches = chunk(uniqueTexts, 90);
  for (let index = 0; index < batches.length; index += 1) {
    const batch = batches[index]!;
    console.log(`Translating batch ${index + 1}/${batches.length} (${batch.length})...`);
    const vi = await translateBatch(batch);
    batch.forEach((text, idx) => translated.set(text, vi[idx]!));
    // Gentle pacing.
    await new Promise((resolve) => setTimeout(resolve, 250));
  }

  const viById = new Map<string, TranslationRow>();
  seedIdeas.forEach((idea) => {
    const row: TranslationRow = { summary: "", details: "" };
    const summaryKey = stripCites(idea.summary);
    const detailsKey = stripCites(idea.details);
    row.summary = translated.get(summaryKey) ?? summaryKey;
    row.details = translated.get(detailsKey) ?? detailsKey;
    viById.set(idea.id, row);
  });

  const sortedIds = Array.from(viById.keys()).sort((a, b) => a.localeCompare(b));
  const lines: string[] = [];
  lines.push("/* This file is generated by `npm run translate:vi`. */");
  lines.push("/* Do not edit by hand. */");
  lines.push("");
  lines.push("export type ViSeedDescription = { summary: string; details: string };");
  lines.push("export const viSeedDescriptions: Record<string, ViSeedDescription> = {");
  sortedIds.forEach((id) => {
    const entry = viById.get(id)!;
    lines.push(`  ${JSON.stringify(id)}: {`);
    lines.push(`    summary: \`${escapeTsString(entry.summary)}\`,`); // template string keeps quotes/simple escapes manageable
    lines.push(`    details: \`${escapeTsString(entry.details)}\`,`);
    lines.push("  },");
  });
  lines.push("};");
  lines.push("");

  const outPath = path.resolve(process.cwd(), "src/lib/viSeedDescriptions.generated.ts");
  await writeFile(outPath, lines.join("\n"), "utf8");
  console.log(`Wrote ${outPath}`);
};

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
